[package]
name = "samp"
version = "0.1.2"
authors = ["ZOTTCE <zottce@gmail.com>"]
description = "Tools to develop SA:MP plugins"
license = "MIT"
repository = "https://github.com/zottce/samp-rs/"
readme = "../readme.md"
edition = "2021"

[features]
default = []
encoding = ["samp-sdk/encoding"]
async = ["samp-async"]

[dependencies]
samp-sdk = { path = "../samp-sdk", version = "0.9.2" }
samp-codegen = { path = "../samp-codegen", version = "0.1.1" }
samp-runtime = { path = "../samp-runtime", version = "0.1.0" }
samp-async = { path = "../samp-async", version = "0.1.0", optional = true }
fern = "0.6.1"
log = "0.4.17"

[package.metadata.docs.rs]
features = ["encoding"]
default-target = "i686-pc-windows-msvc"